services:

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgresql
    networks:
      - db_network
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped

  postgresql:
    container_name: postgres
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - db_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

networks:
  db_network:
    driver: bridge

volumes:
  postgres_data: